apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: vn-postgres
  namespace: vn-data
spec:
  instances: 1

  storage:
    size: 5Gi

  bootstrap:
    initdb:
      database: vn_app
      owner: vn_app
      secret:
        name: vn-postgres-app-user
